services:
  bacnet-device:
    image: fh1ch/bacstack-compliance-docker
    ports:
      - "47808:47808/udp"

  bacnet-client:
    image: ${NODE_IMAGE:-node:20}
    working_dir: /bacnet
  #  user: node
    volumes:
      - .:/bacnet
    command: |
      bash -c "tail -f /dev/null"

